from enum import Enum


class ERepositoryType(str, Enum):
    ABRVIRTUAL = "AbrVirtual"
    AMAZONS3 = "AmazonS3"
    AMAZONS3EXTERNAL = "AmazonS3External"
    AMAZONS3GLACIER = "AmazonS3Glacier"
    AMAZONS3GLACIEREXTERNAL = "AmazonS3GlacierExternal"
    AMAZONSNOWBALLEDGE = "AmazonSnowballEdge"
    AZUREARCHIVE = "AzureArchive"
    AZUREARCHIVESTORAGEEXTERNAL = "AzureArchiveStorageExternal"
    AZUREBLOB = "AzureBlob"
    AZUREDATABOX = "AzureDataBox"
    AZURESTORAGEEXTERNAL = "AzureStorageExternal"
    CLOUD = "Cloud"
    DELLDATADOMAIN = "DellDataDomain"
    ELEVENELEVENS3 = "ElevenElevenS3"
    EXAGRID = "ExaGrid"
    EXTENDABLEREPOSITORY = "ExtendableRepository"
    FOREIGN = "Foreign"
    FUJITSU = "Fujitsu"
    GOOGLEARCHIVESTORAGEEXTERNAL = "GoogleArchiveStorageExternal"
    GOOGLECLOUD = "GoogleCloud"
    GOOGLECLOUDSTORAGEEXTERNAL = "GoogleCloudStorageExternal"
    HPESTOREONCE = "HPEStoreOnce"
    HPSTOREONCE = "HPStoreOnce"
    HPSTOREONCECLOUDBANK = "HPStoreOnceCloudBank"
    IBMCLOUD = "IBMCloud"
    INFINIDAT = "Infinidat"
    LINUXHARDENED = "LinuxHardened"
    LINUXLOCAL = "LinuxLocal"
    NFS = "Nfs"
    PLATFORMSERVICEEXTERNAL = "PlatformServiceExternal"
    PLATFORMSERVICEVMBAPI = "PlatformServiceVmbApi"
    QUANTUMDXI = "QuantumDXi"
    S3COMPATIBLE = "S3Compatible"
    S3GLACIERCOMPATIBLE = "S3GlacierCompatible"
    S3INTEGRATED = "S3Integrated"
    SANSNAPSHOTONLY = "SanSnapshotOnly"
    SMB = "Smb"
    TAPE = "Tape"
    VEEAMDATACLOUDVAULT = "VeeamDataCloudVault"
    VEEAMDATACLOUDVAULTARCHIVE = "VeeamDataCloudVaultArchive"
    VEEAMDATACLOUDVAULTAWSEXTERNAL = "VeeamDataCloudVaultAwsExternal"
    VEEAMDATACLOUDVAULTAZUREEXTERNAL = "VeeamDataCloudVaultAzureExternal"
    VEEAMVAULT = "VeeamVault"
    WASABICLOUD = "WasabiCloud"
    WINLOCAL = "WinLocal"

    def __str__(self) -> str:
        return str(self.value)
